replicaCount: 1

secret:
  mongodb:
    name: my-mongodb-secret
  react:
    name: my-react-secret

mongodb:
  port: 27017
  nodePort: 30017 

imgs:
  FRONT_IMG: dangdang42/myportfolio-front:latest
  NODEJS_IMG: dangdang42/myportfolio-nodejs:latest
  NGINX_IMG: dangdang42/myportfolio-nginx:latest
  # FRONTEND_IMG: dangdang42/myportfolio-frontend:latest
  FASTAPI_IMG:  dangdang42/myportfolio-fastapi:latest
  CHATBOT_IMG: dangdang42/myportfolio-backend-chatbot:latest