apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-nodejs
  namespace: myportfolio
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-nodejs
  template:
    metadata:
      labels:
        app: myportfolio-nodejs
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-nodejs
          image: {{ .Values.imgs.NODEJS_IMG}}
          ports:
            - containerPort: 5173

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-nginx
  namespace: myportfolio
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-nginx
  template:
    metadata:
      labels:
        app: myportfolio-nginx
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-nginx
          image: {{ .Values.imgs.NGINX_IMG}}
          ports:
            - containerPort: 80

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myportfolio-front
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: myportfolio-front
#   template:
#     metadata:
#       labels:
#         app: myportfolio-front
#     spec:
#       initContainers:
#         - name: wait-for-mongodb
#           image: busybox
#           command: 
#             - "sh"
#             - "-c"
#             - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
#       containers:
#         - name: myportfolio-front
#           image: {{ .Values.imgs.FRONT_IMG}}
#           ports:
#             - containerPort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
  namespace: myportfolio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-fastapi
  template:
    metadata:
      labels:
        app: myportfolio-fastapi
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-fastapi
          image: {{ .Values.imgs.FASTAPI_IMG }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PASS
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_COLLECTION_FASTAPI
            - name: REACT_APP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_HOST
            - name: REACT_APP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_PORT
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deploy
  namespace: myportfolio
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-chatbot
  template:
    metadata:
      labels:
        app: myportfolio-chatbot
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-backend-chatbot
          image: {{ .Values.imgs.CHATBOT_IMG }}
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PASS
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_COLLECTION_CHATBOT
            - name: REACT_APP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_HOST
            - name: REACT_APP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_PORT
