apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-frontend
  template:
    metadata:
      labels:
        app: myportfolio-frontend
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-frontend
          image: {{ .Values.imgs.FRONTEND_IMG }}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_FASTAPI_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.react.name }}
                  key: REACT_APP_FASTAPI_URL
            - name: REACT_APP_CHATBOT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.react.name }}
                  key: REACT_APP_CHATBOT_URL
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-fastapi
  template:
    metadata:
      labels:
        app: myportfolio-fastapi
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-fastapi
          image: {{ .Values.imgs.FASTAPI_IMG }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PASS
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_COLLECTION_FASTAPI
            - name: REACT_APP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_HOST
            - name: REACT_APP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_PORT
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myportfolio-chatbot
  template:
    metadata:
      labels:
        app: myportfolio-chatbot
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: 
            - "sh"
            - "-c"
            - "until nc -z -v -w30 mongodb-service 27017; do echo 'Waiting for mongodb...'; sleep 5; done;"
      containers:
        - name: myportfolio-backend-chatbot
          image: {{ .Values.imgs.CHATBOT_IMG }}
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PASS
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: MONGO_COLLECTION_CHATBOT
            - name: REACT_APP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_HOST
            - name: REACT_APP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.mongodb.name }}
                  key: REACT_APP_PORT
