apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: app
          image: "mongo:4.4"
          ports:
            - containerPort: 27017
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.secret.mongodb.name }}
          env:
            - name: TZ
              value: Asia/Seoul
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Values.secret.mongodb.name }}
            #       key: MONGO_USER
            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Values.secret.mongodb.name }}
            #       key: MONGO_PASS
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
          # args:
          #   - "--auth"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
   