apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001